server:
  port: 8080
spring:
  application:
    name: carwashSpring
  datasource:
    url: jdbc:postgresql://localhost:5432/db_car_wash
    username: ${LOGIN POSTGRE}
    password: ${PASSWORD_POSTGRE}
  jpa:
    show: true
    hibernate:
      ddl-auto: validate
    open-in-view: true
    output:
        ansi:
          enabled=ALWAYS:
  liquibase:
    enabled: true
  change-log:
    classpath: db/changelog/db.changelog-master.yaml

source:
  driver-class-name: org.postgresql.Driver

logging:
  level:
    root: INFO
  file:
    name: LogCarWash



security:
  jwtSecretExpiration: 86400000
  jwtSecret: 841D8A6C80CBA4FCAD32D5367C18C53B





